### ISSUE TITLE
FileMaintenance.ps1 - bulk archive option

### ISSUE THREAD

**Issue by heewey** [7k2mpa/FileMaintenace#14]
Hello,

I would like to use your FileMaintenance.ps1 as the logs archive tool which allows specifying for 7zip command line an option compress wildcard files in multithread option.

From https://www.dotnetperls.com/7-zip-examples
example:
7z a -t7z archive.7z *.exe *.dll -ms -mmt

In current version FileMaintenance.ps1 is used CommonFunctions.ps1 where is specified 7zip command like:
.\7z.exe a $ActionTo $ActionFrom -t"$7zType" 2>&1

would be fine to define a parameter for -mmt and -ms for 7zip and add an option to specify archiveName only, which can help make faster handling in the case when you try to archive hundreds of small files.

Thanks in advance and best regards,
heewey.

**Comment by 7k2mpa** [comment]
Hello heewey,

According to 7zip command line manual, -mmt on  switch make to process in multi thread and offer better performance.
I will add -mmt switch to 7zip command.

> mt=[off | on | {N}]
> 
>     Sets multithread mode. If you have a multiprocessor or multicore system, you can get a speed increase with this switch. This option affects only compression (with any method) and decompression of BZip2 streams. Each thread in the multithread mode uses 32 MB of RAM for buffering. If you specify {N}, 7-Zip tries to use N threads.
> 


By the way, I could not find -ms switch on (official?) command line manual.

Regards.

https://sevenzip.osdn.jp/chm/cmdline/switches/method.htm

**Comment by heewey** [comment]
Hello, 

good work, when will be released?

Regarding -ms switch, it should create a solid archive. Nothing important and at the moment out of my scope.

Example ms command line:
`7z a -t7z archive.7z *.exe *.dll -ms -mmt`

7z:         name of executable
a:          archive command specified
-t7z:       use 7z file type (less compatible and smaller results)
archive.7z: destination archive file
*.exe:      include all *.exe files in directory in new archive
*.dll:      include all *.dll files in new archive
**-ms:        create solid archive (default)**
-mmt:       multithread the operation (faster)

**Comment by 7k2mpa** [comment]
Hello.

Thanks for information.
I added -mmt on switch to 7zip sections.

**Comment by heewey** [comment]
Thanks.
