### ISSUE TITLE
FileMaintenace - escape option when processing

### ISSUE THREAD

**Issue by heewey** [7k2mpa/FileMaintenace#16]
Hello, 

I would like to consider another approach when the FileMaintenece shell is running in the case when it processes lots of files and you have to "cancel" the process for some reason and one of the operations is to "delete the old file". The current behavior accepts file deletion, but the new archive was not finished, then you are losing unfortunately some files because the unfinished archive is corrupted, and the delete action was finished.

It should at first archive all files and then delete them.

In my case, I was surprised that the archive file was "archive_name_timestamp.zip.tmp" after process canceling from shell.

**Comment by 7k2mpa** [comment]
Hello.

I understand your concerns.
But it is difficult for the scripts architecture to make change the script.


In your case, this method is suitable for you.


Wrapper.ps1 script calls FileMaintenance.ps1 script.

In the command file for wrapper.ps1


command.txt
-TargetFolder hoge -PreAction Archive,AddTimeStamp -Action none
-TargetFolder hoge -PreAction none -Action Delete


.\Wrapper.ps1 -CommandPath .\FileMaintenance.ps1 -CommandFile .\Command.txt

1st line makes to archive files at first.
2nd line makes to delete all files archived.

Regards.
