### ISSUE TITLE
FileMaintenance - archive and then delete with the same list of variables in two steps in command.txt using Wrapper.ps1

### ISSUE THREAD

**Issue by heewey** [7k2mpa/FileMaintenace#18]
I was testing the behavior when the command is separated into two lines - the first one is for archiving and the second is to delete the file after successful archive creation. 
The most philosophical question was when the archive process runs more than X hours (let's say during the night, over midnight), whether it is possible to delete some file that was not archived because the regex pattern did not count with the correct time range - and the answer is yes, you can delete some file without previous archiving because the delete process is after the archiving with a new list of files.

Future request - add an option to "archive" first and "delete" after successful archive creation with the same variable list.

**Comment by 7k2mpa** [comment]
Thanks heewey.

The scripts architecture is

Get-Object(list up files for processing)

Main loop start
 preaction (compress,archive,etc..)
 action (delete,move,copy,etc)
 postaction (null clear,etc)
Main loop end



And for your request.
I should add a new loop for archiving.

I will add this future next version.


Get-Object(list up files for processing)

Pre loop start
 preaction (archive)
Pre loop end

Main loop start
 preaction (compress,etc..)
 action (delete,move,copy,etc)
 postaction (null clear,etc)
Main loop end



Regards.

**Comment by 7k2mpa** [comment]
It is not perfect solution.
It may need long time to process for processing many files.

With wapper.ps1

Command.txt

-TargetFolder folder -PreAction Archive -Action Move -MoveToFolder tempfolder
-TargetFolder tempfolder -Action Delete
-TargetFolder tempfolder -Action DeleteEmptyFolders

**Comment by heewey** [comment]
Hello,

I really appreciate your work, your script is unique for log maintenance in windows.

It seems to would be a performance issue here, in the case when the script will list more 500 000 files in subfolders.

Is possible to speed it up with some --quiet parameter?

I will test the new version soon as possible for my purpose.

Regards heewey

**Comment by 7k2mpa** [comment]
Hello.

-NoLog2EventLog suppress writing event logging, and it may be possible to speed up processing.

Regards.

**Comment by heewey** [comment]
Hello,

I need more help with the correct Command sequence in the case, when I need to create an archive from all files in C:\test\xml older than 30 days and archive file storing to C:\test\archive  as "archive+timestamp.zip" and using your suggested option to protect deleting files accidentally out of time range during long archive execution in C:\test\tempfolder and do all these steps quiet.

Thanks in andvance,
heewey.
heewey.

**Comment by heewey** [comment]
Hello,

the quiet parameter was not brought a higher speed. Moving to the temp folder was fast, but the archiving process took too much time. Seems to be a time to do a code review. Anyway, this approach prevents deleting files out of time range.

Thanks, and I´m hoping for a version. 4.0 in a short time.
